### ISSUE TITLE
simple CLI interface

### ISSUE THREAD

**Issue by akimfromparis** [DoormatIka/twitter-scraper#1]
Hello Doormatlka,

Thank you for your work. I am not used to the workflow of TS. I believe I did a npm i -g twitter-scraper

Any chance, we can use with CLI like [drawrowfly/tiktok-scraper ](https://github.com/drawrowfly/tiktok-scraper)?

Thank you!
Best

**Comment by DoormatIka** [comment]
Hi AkimParis,

Thank you for checking out this library!
I will add the CLI shipped with other features I plan to do.

**Comment by DoormatIka** [comment]
It's been implemented with the v1.1.0 update. I'll add more features as time goes on
![image](https://user-images.githubusercontent.com/68234036/219869904-40ef326d-09dc-43dc-9929-667a145284a5.png)
